[project]
name = "analyze-minifier"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.analyze-minifier]
path = "contracts/analyze-minifier.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
